# BigBang specific values for fluent-bit.
#
# -- Configuration for Elasticsearch interaction
elasticsearch:
  # -- Name is only used at the BB level for host templating
  name: ""

# -- Configuration for Istio interaction
istio:
  # -- Toggle currently only controls NetworkPolicies
  enabled: false
  hardened:
    enabled: false
    outboundTrafficPolicyMode: "REGISTRY_ONLY"
    customServiceEntries: []
      # - name: "allow-google"
      #   enabled: true
      #   spec:
      #     hosts:
      #       - google.com
      #       - www.google.com
      #     location: MESH_EXTERNAL
      #     ports:
      #       - number: 443
      #         protocol: TLS
      #         name: https
      #         resolution: DNS
    customAuthorizationPolicies: []
    # - name: "allow-nothing"
    #   enabled: true
    #   spec: {}
  # -- Default peer authentication setting
  mtls:
    # -- STRICT = Allow only mutual TLS traffic
    # PERMISSIVE = Allow both plain text and mutual TLS traffic
    mode: STRICT

networkPolicies:
  enabled: false
  # See `kubectl cluster-info` and then resolve to IP
  controlPlaneCidr: 0.0.0.0/0
  additionalPolicies: []

# -- Additional Outputs for Big Bang,
# these are wrappers to simplify the config of outputs and
# extend whatever is specified under the `outputs` values
additionalOutputs:
  # -- Option to disable the default elastic output configured under `outputs`,
  # this only works at the Big Bang chart level
  disableDefault: false
  # -- Options to enable an additional elastic output
  elasticsearch:
    host: ""
    port: 9200
    match:
      - "kube.*"
      - "host.*"
    user: "elastic"
    password: ""
    # -- Toggle on TLS
    tls: true
    # -- Verify TLS certificates, requires a caCert to be specified
    tlsVerify: false
    # -- Full ca.crt specified as multiline string, see example
    caCert: ""
    # caCert: |
    # /  -----BEGIN CERTIFICATE-----
    #   MIIE4jCCAsqgAwIBAgIBATANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZzZm8t
    #   Y2EwHhcNMTkxMjIwMDAxNjI1WhcNMjEwNjIwMDAxNjIxWjARMQ8wDQYDVQQDEwZz
    # /  -----END CERTIFICATE-----
    # -- Reference configuration parameters provided by Fluentbit - https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
    additionalConfig: {}
    # Customer values are used for: Name, Host, Port, HTTP_User, HTTP_Passwd, tls, tls.verify, and tls.ca_file
    #   Specify these values with the above host, port, user, password, tls, tlsVerify, and caCert
    # Defaults are set for: Match, Logstash_Format, Logstash_Prefix, Retry_Limit, Retry_Limit
    #   Overriding these values is not supported here, use `outputs` if you do not want to use the defaults
    # Example:
    #   Buffer_Size: 8KB
  # -- Options to enable a fluentd output
  fluentd:
    host: ""
    port: 24224
    match:
      - "kube.*"
      - "host.*"
    user: ""
    password: ""
    # -- Overridden by username and password
    sharedKey: ""
    # -- Toggle on TLS
    tls: true
    # -- Verify TLS certificates, requires a caCert to be specified
    tlsVerify: false
    # -- Full ca.crt specified as multiline string, see example
    caCert: ""
    # caCert: |
    # /  -----BEGIN CERTIFICATE-----
    #   MIIE4jCCAsqgAwIBAgIBATANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZzZm8t
    #   Y2EwHhcNMTkxMjIwMDAxNjI1WhcNMjEwNjIwMDAxNjIxWjARMQ8wDQYDVQQDEwZz
    # /  -----END CERTIFICATE-----
    # -- Reference configuration parameters provided by Fluentbit - https://docs.fluentbit.io/manual/pipeline/outputs/forward
    additionalConfig: {}
    # Customer values are used for: Time_as_Integer, Upstream, Tag, Send_options, Require_ack_response, Compress, Empty_Shared_Key, Self_Hostname, tls.debug, tls.crt_file, tls.key_file, tls.key_passwd
    #   Specify these values with the above host, port, user, password, tls, tlsVerify, and caCert
    # Defaults are set for: Name, Match, Host, Port, Username, Password, Shared_Key, tls, tls.verify, tls.ca_file
    # Example:
    #   Self_Hostname: "custom_value"
  # -- Options to enable a loki output
  loki:
    host: ""
    port: 3100
    match:
      - "kube.*"
      - "host.*"
    # -- User and Password are optional - only required if running proxy in front of Loki,
    # see https://grafana.com/docs/loki/latest/operations/authentication/
    user: ""
    password: ""
    # -- Toggle on TLS - disabled by default to support in cluster Loki
    tls: false
    # -- Verify TLS certificates, requires a caCert to be specified
    tlsVerify: false
    # -- Full ca.crt specified as multiline string, see example
    caCert: ""
    # caCert: |
    # /  -----BEGIN CERTIFICATE-----
    #   MIIE4jCCAsqgAwIBAgIBATANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZzZm8t
    #   Y2EwHhcNMTkxMjIwMDAxNjI1WhcNMjEwNjIwMDAxNjIxWjARMQ8wDQYDVQQDEwZz
    # /  -----END CERTIFICATE-----
    # -- Reference configuration parameters provided by Fluentbit - https://docs.fluentbit.io/manual/pipeline/outputs/loki
    additionalConfig: {}
    # Customer values are used for: host, post, http_user, http_passwd, tls, tls.verify, and tls.ca_file
    #   Specify these values with the above host, port, user, password, tls, tlsVerify, and caCert
    # Defaults are provided for Name, Match, Retry_Limit, and auto_kubernetes_labels
    #   Overriding these values is not supported here, use `outputs` if you do not want to use the defaults
    # Example:
    #   tenant_id: "custom_value"
  # -- Options to enable a S3 output
  s3:
    bucket: ""
    region: "us-east-1"
    match:
      - "kube.*"
      - "host.*"
    aws_access_key_id: ""
    aws_secret_access_key: ""
    # -- Reference an existing secret with your access and secret key,
    # must contain key values pairs for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    existingSecret: ""
    # -- Reference configuration parameters provided by Fluentbit - https://docs.fluentbit.io/manual/pipeline/outputs/s3
    additionalConfig:
      total_file_size: 1M
      upload_timeout: 1m
      use_put_object: On
    # Defaults are set for: Name, Match, bucket, region
    # For other custom values, checkout the plugin link above
    # Example:
    #   role_arn: "custom_value"

# -- Options to configure hostPath mounted storage buffer for production use
# Specified in fluentbit service configuration section below
# see https://docs.fluentbit.io/manual/administration/buffering-and-storage
# storage_buffer:
#   path: /var/log/flb-storage/

# -- Limits the number of Chunks that exists in the file system for a certain logical output destination.
# If one destination reaches the storage.total_limit_size limit, the oldest Chunk from the queue for that logical output destination will be discarded.
# see https://docs.fluentbit.io/manual/administration/buffering-and-storage
storage:
  total_limit_size: 10G

# -- Toggle for Openshift, currently only controls NetworkPolicy changes
openshift: false

# -- List of enabled Big Bang log storage package(s), used to control networkPolicies and auth only
loki:
  enabled: false
elasticsearchKibana:
  enabled: false

# -- Values used for Big Bang CI testing
bbtests:
  # -- Toggles test manifests
  enabled: false
  # Values used for Big Bang script based testing
  scripts:
    # -- Image used to run script tests, must include curl and jq
    image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
    # -- Envs that are passed into the script runner pod
    envs:
      # -- Hostname/port to contact Fluentbit
      fluent_host: "http://{{ include \"fluent-bit.fullname\" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.upstream.service.port }}"
      # -- Version that should be running
      desired_version: "{{ .Values.upstream.image.tag }}"

# Overrides for default upstream chart values for fluent-bit.
upstream:
  image:
    repository: registry1.dso.mil/ironbank/opensource/fluent/fluent-bit
    pullPolicy: Always
    tag: 4.0.8

  testFramework:
    enabled: false

  imagePullSecrets:
  - name: private-registry

  nameOverride: "fluent-bit"

  securityContext:
    runAsUser: 0
    readOnlyRootFilesystem: true
    privileged: false
    seLinuxOptions:
      type: spc_t
    capabilities:
      drop:
        - ALL

  prometheusRule:
    additionalLabels: {}
    # Rules to be deployed
    rules:
    - alert: fluentbitJobAbsent
      annotations:
        message: "Fluent Bit job not present for 10m"
      expr: absent(up{job="fluentbit", namespace="logging"})
      for: 10m
      labels:
        severity: critical
    - alert: FluentdLowNumberOfPods
      expr: |-
        avg without (instance) (up{job="fluentbit"}) < .20
      for: 10m
      annotations:
      labels:
        severity: critical
    - alert: LogsNotFlowing
      expr: |-
        sum(rate(fluentd_output_status_num_records_total{}[4h])) by (tag) < .001
      for: 30m
      annotations:
      labels:
        severity: critical
    - alert: NoOutputBytesProcessed
      expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
      annotations:
        message: |
          Fluent Bit instance {{ $labels.instance }}'s output plugin {{ $labels.name }} has not processed any
          bytes for at least 15 minutes.
      for: 15m
      labels:
        severity: critical

  extraVolumes:
  # -- Mount /var/log/flb-storage/ for the storage buffer, recommended for production systems.
    - hostPath:
        path: /var/log/flb-storage/
        type: DirectoryOrCreate
      name: flb-storage

  extraVolumeMounts:
  # -- Mount /var/log/flb-storage/ for the storage buffer, recommended for production systems.
    - mountPath: /var/log/flb-storage/
      name: flb-storage
      readOnly: false

  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush | default "1" }}
          Log_Level {{ .Values.logLevel | default "info" }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort | default "2020" }}
          # -- Setting up storage buffer on filesystem and slightly upping backlog mem_limit value.
          storage.path /var/log/flb-storage/
          storage.sync normal
          storage.backlog.mem_limit 15M
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          # -- Excluding fluentbit logs from sending to ECK, along with gatekeeper-audit logs which are shipped by clusterAuditor.
          Exclude_Path /var/log/containers/*fluent*.log
          Parser containerd
          Tag kube.*
          Mem_Buf_Limit 50MB
          Skip_Long_Lines On
          storage.type filesystem

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On
          storage.type filesystem

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: ""

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: ""

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L

      [PARSER]
          Name containerd
          Format regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
          Time_Keep On

      [PARSER]
          Name        syslog
          Format      regex
          Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
          Time_Key    time
          Time_Format %b %d %H:%M:%S

  daemonSetVolumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: etcmachineid
      mountPath: /etc/machine-id
      readOnly: true

  hotReload:
    image:
      repository: registry1.dso.mil/ironbank/opensource/jimmidyson/configmap-reload
      tag: v0.15.0
