{{- if and .Values.networkPolicies.enabled .Values.istio.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: logging
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: logging 
{{- end }}