{{- $additionalElastic := (and .Values.additionalOutputs.elasticsearch.host .Values.additionalOutputs.elasticsearch.user .Values.additionalOutputs.elasticsearch.password .Values.additionalOutputs.elasticsearch.port) }}
{{- if and $additionalElastic .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-elastic-egress-fluentbit
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
    ports:
    - port: {{ .Values.additionalOutputs.elasticsearch.port }}
      protocol: TCP 
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  policyTypes:
  - Egress
{{- end }}