{{- with .Values.additionalOutputs.s3 }}
{{- $additionalS3 := (and .bucket .region (or (and .aws_access_key_id .aws_secret_access_key) .existingSecret) ) }}
{{- if and $additionalS3 $.Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-s3-egress-fluentbit
  namespace: {{ $.Release.Namespace }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
    ports:
    - port: 443
      protocol: TCP 
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  policyTypes:
  - Egress
{{- end }}
{{- end }}