{{- if and .Values.elasticsearchKibana.enabled (.Capabilities.APIVersions.Has "kyverno.io/v1") -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-elastic-password-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    policies.kyverno.io/title: Sync Elastic password secret
    policies.kyverno.io/category: Fluentbit
    policies.kyverno.io/subject: Elastic password secret
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-elastic-password-secret
    match:
      resources:
        kinds:
        - Namespace
        selector:
          matchLabels:
             kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
    generate:
      kind: Secret
      name: logging-ek-es-elastic-user
      namespace: {{ .Release.Namespace }}
      synchronize: true
      clone:
        namespace: logging
        name: logging-ek-es-elastic-user
{{- end }}
